### ISSUE TITLE
Bulk-edit gear

### ISSUE THREAD

**Issue by aarondunn** [MGHollander/strava-bulk-edit#13]
Allow past activities to be modified to bulk add/edit gear associated.

**Additional context**
I recently imported data from another fitness app, to track miles on running shoes/bike would require manually editing 1,000+ rides. This tool could solve that!

**Comment by MGHollander** [comment]
Hi @aarondunn,

Thank you for your suggestions. #3 also covers this request.

**Comment by MGHollander** [comment]
Hi @aarondunn,

It took a bit longer, but I've added three new fields that can be updated. The Chrome extension update was published yesterday. I hope it helps. 

Please let me know if your have any other ideas.

**Comment by aarondunn** [comment]
Wow thanks, this is amazing!
