### ISSUE TITLE
Undo bulk equipment change

### ISSUE THREAD

**Issue by SpinGordy** [MGHollander/strava-bulk-edit#19]
I seem to have changed my bike on ALL my rides ...

Is there a way to undo the change and recover my old data or am I stuck with the change?

Cheers!

**Comment by MGHollander** [comment]
You can try to use the filter to get certain rides, but I assume you wish to undo all changes for a period of time.

At the moment there is no way to filter activities on date. I have created issue #16 to add some additional filters, but I'm not sure when I will build this.

**Comment by SpinGordy** [comment]
Thanks Marc

I was hoping for a basic "undo" to retrieve my original data but never mind!

I'll just have to live with my stupidity!

Cheers

Gordon Riley

----------------------------------------

**Comment by MGHollander** [comment]
That's not possible, indeed :-). The plugin does nothing more then opening and updating the activities one by one. Nothing fancy there.

**Comment by RobertoHerradura** [comment]
This addon works...but it really needs an UNDO and DATE filter please, thank you .

**Comment by MGHollander** [comment]
@RobertoHerradura 
Building an undo feature will be a lot of work, since the plugin needs to keep it's own history of changes that have been made. I'm not planning to build such a feature.
